name: PHP Unit Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "v20.11.1"

      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          dev: "no"

      - name: Install two-factor-provider-webauth Composer Dependencies
        uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565 # 3.1.0
        with:
          working-directory: plugins/two-factor-provider-webauthn

      - name: "Run tests"
        run: |
          composer test
